source 'https://rubygems.org'
ruby "2.1.2"

gem 'coffee-rails'
gem 'ember-rails'
gem 'ember-source'
gem 'emblem-rails'
gem 'faker'
gem 'haml-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'rails_12factor'
gem 'pg'
gem 'puma'
gem 'rails', '4.1.4'
gem 'sass-rails'
gem 'uglifier'
gem 'pry-rails'
